config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'home/index'
  root to: 'home#index'
  
  resources :appointments
  resources :doctors
  resources :patients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  validates :doctor_id, :patient_id, presence: true
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	validates :name, :phone, :spacialization, presence: true
	has_many :appointments
    has_many :doctors, :through => :appointments
end

app/models/patient.rb
class Patient < ApplicationRecord
	validates :name, :phone, presence: true
	has_many :appointments
    has_many :patients, :through => :appointments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to root_path, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:doctor_id, :patient_id, :diseases, :appointment_date, :appointment_time)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to root_path, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:name, :phone, :specialization)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  	@doctor = Doctor.new
  	@patient = Patient.new
  	@appointment = Appointment.new

  	@appointments = Appointment.all
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to root_path, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(level)
	    case level
	      when 'notice' then "alert alert-info"
	      when 'success' then "alert alert-success"
	      when 'error' then "alert alert-danger"
	      when 'alert' then "alert alert-warning"
	    end
    end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">

      <%= form_with(model: appointment, local: true) do |form| %>
        <% if appointment.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

            <ul>
              <% appointment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :appointment_date %><br>
          <%= form.date_select :appointment_date %>
        </div>

        <div class="form-group">
          <%= form.label :appointment_time %><br>
          <%= form.time_select :appointment_time %>
        </div>
  
        <div class="form-group">
          <%= form.label :doctor_id %>
          <%= form.select :doctor_id, Doctor.all.collect {|t| [t.name, t.id]}, {prompt: '-- Select Doctor Name --'}, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :patient_id %>
          <%#= form.number_field :patient_id, id: :appointment_patient_id, class: 'form-control' %>
          <%= form.select :patient_id, Patient.all.collect {|t| [t.name, t.id]}, {prompt: '-- Select Patient Name --'}, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :diseases %>
          <%= form.text_field :diseases, id: :appointment_diseases, class: 'form-control' %>
        </div>

        <div class="actions">
          <%= form.submit class: 'btn btn-success' %> | <%= link_to 'Back', appointments_path, class: 'btn btn-primary' %>
        </div>

      <% end %>

    </div>   
  </div>
</div>


<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker();
  });
</script>

app/views/appointments/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12"><br/>
			<h1>Editing Appointment</h1>

			<%= render 'form', appointment: @appointment %>

			<%#= link_to 'Show', @appointment %> 
			<%#= link_to 'Back', appointments_path %>
		</div>
	</div>
</div>

app/views/appointments/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <p id="notice"><%= notice %></p>

      <h1>Appointments</h1>

        <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th>Appointment Date & Time</th>
              <th>Doctor Name</th>
              <th>Patient Name</th>
              <th>Diseases</th>
              <th>Actions</th>
            </tr>
          </thead>

        <tbody>
          <% @appointments.each do |appointment| %>
            <tr>
              <!-- <td><%#= appointment.appointment_date %></td> -->
              <td><%= appointment.appointment_time %></td>
              <td><%= appointment.doctor.name %></td>
              <td><%= appointment.patient.name %></td>
              <td><%= appointment.diseases %></td>
              <td><%= link_to 'Show', appointment %> |
              <%= link_to 'Edit', edit_appointment_path(appointment) %> |
              <%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>

      <%= link_to 'New appointment', new_appointment_path, class: 'btn btn-success' %>

    </div>
  </div>
</div>

app/views/appointments/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12"><br/>
			<h1 class="title text-center">New appointment</h1>

			<%= render 'form', appointment: @appointment %>
		</div>
	</div>
</div>

app/views/appointments/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<p id="notice"><%= notice %></p>
	
			<!-- <p>
			  <strong>Appointment Date:</strong>
			  <%#= @appointment.appointment_date %>
			</p> -->
			<p>
			  <strong>Appointment Date & Time:</strong>
			  <%= @appointment.appointment_time %>
			</p>
			<p>
			  <strong>Doctor Name:</strong>
			  <%= @appointment.doctor.name %>
			</p>

			<p>
			  <strong>Patient Name:</strong>
			  <%= @appointment.patient.name %>
			</p>

			<p>
			  <strong>Diseases:</strong>
			  <%= @appointment.diseases %>
			</p>

			<%= link_to 'Edit', edit_appointment_path(@appointment), class: 'btn btn-info' %> |
			<%= link_to 'Back', appointments_path, class: 'btn btn-secondary' %>
		</div>
	</div>
</div>

app/views/bookings/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<p id="notice"><%= notice %></p>
	
			<p>
			  <strong>Appointment Date:</strong>
			  <%= @booking.appointment_date %>
			</p>
			<p>
			  <strong>Doctor Name:</strong>
			  <%= @booking.doctor_id %>
			</p>

			<p>
			  <strong>Patient Name:</strong>
			  <%= @booking.patient_id %>
			</p>

			<p>
			  <strong>Diseases:</strong>
			  <%= @booking.diseases %>
			</p>

			<%= link_to 'Edit', edit_booking_path(@booking), class: 'btn btn-info' %> |
			<%= link_to 'Back', bookings_path, class: 'btn btn-secondary' %>
		</div>
	</div>
</div>

app/views/doctors/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= form_with(model: doctor, local: true) do |form| %>
        <% if doctor.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

            <ul>
            <% doctor.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, id: :doctor_name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :phone %>
          <%= form.text_field :phone, id: :doctor_phone, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :specialization %>
          <%= form.text_field :specialization, id: :doctor_specialization, class: 'form-control' %>
        </div>

        <div class="actions">
          <%= form.submit class: 'btn btn-success' %> | <%= link_to 'Back', doctors_path, class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/doctors/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1>Editing Doctor</h1>

			<%= render 'form', doctor: @doctor %>
		</div>
	</div>
</div>


<%#= link_to 'Show', @doctor %> 
<%#= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
<p id="notice"><%= notice %></p>

<h1>Doctors</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Specialization</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.phone %></td>
        <td><%= doctor.specialization %></td>
        <td><%= link_to 'Show', doctor %> | 
        <%= link_to 'Edit', edit_doctor_path(doctor) %> |
        <%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path, class: 'btn btn-success' %>
</div>
  </div>
</div>

app/views/doctors/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12"><br/>
			<h1 class="title text-center">New Doctor</h1>

			<%= render 'form', doctor: @doctor %>
		</div>
	</div>
</div>

app/views/doctors/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @doctor.phone %>
</p>

<p>
  <strong>Specialization:</strong>
  <%= @doctor.specialization %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor), class: 'btn btn-info' %> |
<%= link_to 'Back', doctors_path, class: 'btn btn-secondary' %>
</div>
	</div>
</div>

app/views/home/index.html.erb
	<br/>
	<br/>

	<div class="container">
		
		<div class="row">

			<!-- Patient -->
			<div class="col-md-6">
				<h2 class="title text-center" style="color: #0b4380;">PATIENT</h2><hr/><br/>
		      <%= form_for(@patient, local: true) do |form| %>
		        <% if @patient.errors.any? %>
		          <div id="error_explanation">
		            <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

		            <ul>
		            <% @patient.errors.full_messages.each do |message| %>
		              <li><%= message %></li>
		            <% end %>
		            </ul>
		          </div>
		        <% end %>

		        <div class="form-group required">
		          <%= form.label :name, :class=>"control-label" %>
		          <%= form.text_field :name, id: :patient_name, class: 'form-control', required: 'required' %>
		        </div>

		        <div class="form-group required">
		          <%= form.label :phone, :class=>"control-label" %>
		          <%= form.text_field :phone, id: :patient_phone, class: 'form-control', required: 'required' %>
		        </div>

		        <div class="actions text-right">
		          <%= form.submit 'Submit', class: 'btn btn-warning' %>
		        </div>
		      <% end %>
    
			</div>

			<!-- Doctor -->
			<div class="col-md-6">
				<h2 class="title text-center" style="color: #0b4380;">DOCTOR</h2><hr/><br/>
		      <%= form_for(@doctor, local: true) do |form| %>
		        <% if @doctor.errors.any? %>
		          <div id="error_explanation">
		            <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

		            <ul>
		            <% @doctor.errors.full_messages.each do |message| %>
		              <li><%= message %></li>
		            <% end %>
		            </ul>
		          </div>
		        <% end %>

		        <div class="form-group required">
		          <%= form.label :name, :class=>"control-label" %>
		          <%= form.text_field :name, id: :doctor_name, class: 'form-control', required: 'required' %>
		        </div>

		        <div class="form-group required">
		          <%= form.label :phone, :class=>"control-label" %>
		          <%= form.text_field :phone, id: :doctor_phone, class: 'form-control', required: 'required' %>
		        </div>

		        <div class="form-group required">
		          <%= form.label :specialization, :class=>"control-label" %>
		          <%= form.text_field :specialization, id: :doctor_specialization, class: 'form-control', required: 'required' %>
		        </div>

		        <div class="actions text-right">
		          <%= form.submit 'Submit', class: 'btn btn-warning' %>
		        </div>
		      <% end %>
    		</div>


		</div>

		<br/><br/>

		<div class="row">
		<!-- Appointment -->
			<div class="col-md-6">
				<h2 class="title text-center" style="color: #0b4380;">APPOINTMENT</h2><hr/><br/>
		      
    			<%= form_for(@appointment, local: true) do |form| %>
			        <% if @appointment.errors.any? %>
			          <div id="error_explanation">
			            <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

			            <ul>
			              <% @appointment.errors.full_messages.each do |message| %>
			                <li><%= message %></li>
			              <% end %>
			            </ul>
			          </div>
			        <% end %>

			        
			        <div class="form-group required">
			          <%= form.label :doctor_id, :class=>"control-label" %>
			          <%= form.select :doctor_id, Doctor.all.collect {|t| [t.name, t.id]}, {prompt: '-- Select Doctor Name --'}, class: 'form-control', required: 'required' %>
			        </div>

			        <div class="form-group required">
			          <%= form.label :patient_id, :class=>"control-label" %>
			          <%#= form.number_field :patient_id, id: :appointment_patient_id, class: 'form-control' %>
			          <%= form.select :patient_id, Patient.all.collect {|t| [t.name, t.id]}, {prompt: '-- Select Patient Name --'}, class: 'form-control', required: 'required' %>
			        </div>

			        <div class="form-group">
			          <%= form.label :diseases %>
			          <%= form.text_field :diseases, id: :appointment_diseases, class: 'form-control' %>
			        </div>

			        <div class="row">
			        	<div class="col-md-6">
			        		<div class="form-group">
					          <%= form.label :appointment_date %><br>
					          <%= form.date_select :appointment_date, class: 'form-control' %>
					        </div>
			        	</div>
			        	<div class="col-md-6">
			        		<div class="form-group">
					          <%= form.label :appointment_time %><br>
					          <%= form.time_select :appointment_time %>
					        </div>
			        	</div>
			        </div>

			        <div class="actions text-right">
			          <%= form.submit 'Submit', class: 'btn btn-warning' %>
			        </div>

      			<% end %>
			</div>

			<!-- Doctor -->
			<div class="col-md-6">
				<h2 class="title text-center" style="color: #0b4380;">VIEW APPOINTMENT</h2><hr/><br/>
				<table class="table table-bordered table-hover">
			          <thead  style="background-color: #0b4380;">
			            <tr class="title text-center" style="color: #fff;">
			              <th>Appointment Date & Time</th>
			              <th>Doctor Name</th>
			              <th>Patient Name</th>
			              <th>Diseases</th>
			            </tr>
			          </thead>

			        <tbody>
			          <% @appointments.each do |appointment| %>
			            <tr>
			              <!-- <td><%#= appointment.appointment_date %></td> -->
			              <td><%= appointment.appointment_time %></td>
			              <td><%= appointment.doctor.name %></td>
			              <td><%= appointment.patient.name %></td>
			              <td><%= appointment.diseases %></td>
			            </tr>
			          <% end %>
			        </tbody>
		      	</table>
    		</div>
		</div>
	</div>
	<br/>
	<br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>clinic</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

	  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	
	  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="col-md-12">
         <% flash.each do |key, value| %>
              <div class="<%= flash_class(key) %>">
                    <%= value %>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                 <span aria-hidden="true">&times;</span>
                </button>
              </div>
        <% end %> 
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= form_with(model: patient, local: true) do |form| %>
        <% if patient.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

            <ul>
            <% patient.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, id: :patient_name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :phone %>
          <%= form.text_field :phone, id: :patient_phone, class: 'form-control' %>
        </div>

        <div class="actions">
          <%= form.submit class: 'btn btn-success' %> | <%= link_to 'Back', patients_path, class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/patients/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1>Editing Patient</h1>

			<%= render 'form', patient: @patient %>
		</div>
	</div>
</div>


<%#= link_to 'Show', @patient %> 
<%#= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <p id="notice"><%= notice %></p>

      <h1>Patients</h1>

      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Phone</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @patients.each do |patient| %>
            <tr>
              <td><%= patient.name %></td>
              <td><%= patient.phone %></td>
              <td><%= link_to 'Show', patient %> | 
              <%= link_to 'Edit', edit_patient_path(patient) %> | 
              <%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Patient', new_patient_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/patients/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12"><br/>
			<h1 class="title text-center">New Patient</h1>

			<%= render 'form', patient: @patient %>
		</div>
	</div>
</div>

app/views/patients/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<p id="notice"><%= notice %></p>
	
			<p>
			  <strong>Name:</strong>
			  <%= @patient.name %>
			</p>

			<p>
			  <strong>Phone:</strong>
			  <%= @patient.phone %>
			</p>
			<%= link_to 'Edit', edit_patient_path(@patient), class: 'btn btn-info' %> |
			<%= link_to 'Back', patients_path, class: 'btn btn-secondary' %>
		</div>
	</div>
</div>

app/views/shared/_navbar.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
	<h5 class="my-0 mr-md-auto font-weight-normal">clinic</h5>
	<nav class="my-2 my-md-0 mr-md-3">
		<a class="p-2 text-dark" href="/">Home</a>
		<!-- <a class="p-2 text-dark" href="#">Enterprise</a>
		<a class="p-2 text-dark" href="#">Support</a>
		<a class="p-2 text-dark" href="#">Pricing</a> -->
	</nav>
	<%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'btn btn-outline-primary' %>
</div>